"""1-D / N-D mixture kernel parity gate: the 30 `dnp*` / `pnp*` / ND cases
against live-R 4.6.1 reference values recorded in this directory
(`ref_new.txt`, generated by the R script `verify_newr.R`; inputs
`verify_new_x*.txt` / `verify_new_X2.txt`).

Established 0.2.1 result: ALL PASS — every finite value within relative
error 1.2e-15 of R (most are bit-exact); NaNs occur at the same positions
on both sides (R's domain-error semantics, e.g. `dnpnormc` at point-mass
support points and the `pnppois` `lg=TRUE` / `x<0` chain).

The gate reads the gold files from this directory (no external paths) and
exits non-zero on any mismatch.
"""

import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))

from npfixedcomppy import (  # noqa: E402
    dnpnorm, pnpnorm, dnpnormc, dnpt, pnpt, dnpdiscnorm, pnpdiscnorm,
    dnppois, pnppois, dnpdisct, dnpnormND, dnormNDarray,
)

x = np.loadtxt(os.path.join(HERE, "verify_new_x.txt"))
xp = np.loadtxt(os.path.join(HERE, "verify_new_xp.txt"))
X2 = np.loadtxt(os.path.join(HERE, "verify_new_X2.txt"), delimiter=",")
mu0 = np.array([-1.5, -0.2, 0.7, 2.0])
pi0 = np.array([0.1, 0.3, 0.4, 0.2])
mup = np.array([0.5, 1.5, 3.0, 5.0]); pip = np.array([0.1, 0.4, 0.3, 0.2])
MU2 = np.array([[-1.0, 0.5], [0.0, -0.8], [1.2, 0.2]])
stdev, n, df, h = 0.8, 50, 4, 0.05
Sigma = np.array([[1.0, 0.3], [0.3, 0.9]])

py = {}
py["dnpnorm_f"] = dnpnorm(x, mu0, pi0, stdev, False)
py["dnpnorm_l"] = dnpnorm(x, mu0, pi0, stdev, True)
py["pnpnorm_ft"] = pnpnorm(x, mu0, pi0, stdev, True, False)
py["pnpnorm_lt"] = pnpnorm(x, mu0, pi0, stdev, False, False)
py["pnpnorm_flt"] = pnpnorm(x, mu0, pi0, stdev, True, True)
py["pnpnorm_llt"] = pnpnorm(x, mu0, pi0, stdev, False, True)
py["dnpnormc_f"] = dnpnormc(x, mu0, pi0, n, False)
py["dnpnormc_l"] = dnpnormc(x, mu0, pi0, n, True)
py["dnpt_f"] = dnpt(x, mu0, pi0, df, False)
py["dnpt_l"] = dnpt(x, mu0, pi0, df, True)
py["pnpt_ft"] = pnpt(x, mu0, pi0, df, True, False)
py["pnpt_lt"] = pnpt(x, mu0, pi0, df, False, False)
py["pnpt_flt"] = pnpt(x, mu0, pi0, df, True, True)
py["pnpt_llt"] = pnpt(x, mu0, pi0, df, False, True)
py["dnpdiscnorm_f"] = dnpdiscnorm(x, mu0, pi0, stdev, h, False)
py["dnpdiscnorm_l"] = dnpdiscnorm(x, mu0, pi0, stdev, h, True)
py["pnpdiscnorm_ft"] = pnpdiscnorm(x, mu0, pi0, stdev, h, True, False)
py["pnpdiscnorm_lt"] = pnpdiscnorm(x, mu0, pi0, stdev, h, False, False)
py["pnpdiscnorm_flt"] = pnpdiscnorm(x, mu0, pi0, stdev, h, True, True)
py["pnpdiscnorm_llt"] = pnpdiscnorm(x, mu0, pi0, stdev, h, False, True)
# R's exported wrapper is dnppois(x, mu0, pi0, stdev = 1, log); the C++
# binding mirrors that (stdev only reaches the lg normal-term quirk).
py["dnppois_f"] = dnppois(xp, mup, pip, 1.0, False)
py["dnppois_l"] = dnppois(xp, mup, pip, 1.0, True)
py["pnppois_ft"] = pnppois(xp, mup, pip, True, False)
py["pnppois_lt"] = pnppois(xp, mup, pip, False, False)
py["pnppois_flt"] = pnppois(xp, mup, pip, True, True)
py["pnppois_llt"] = pnppois(xp, mup, pip, False, True)
py["dnpdisct_f"] = dnpdisct(x, mu0, pi0, df, h, False)
py["dnpdisct_l"] = dnpdisct(x, mu0, pi0, df, h, True)
py["dnpnormND_f"] = dnpnormND(X2, MU2, pi0[:3], Sigma, False)
py["dnpnormND_l"] = dnpnormND(X2, MU2, pi0[:3], Sigma, True)
py["dnormNDarray_f"] = dnormNDarray(X2, MU2, Sigma, False).ravel(order="F")
py["dnormNDarray_l"] = dnormNDarray(X2, MU2, Sigma, True).ravel(order="F")

# read R reference: name \n count \n values
lines = open(os.path.join(HERE, "ref_new.txt")).read().splitlines()
i = 0
ok = True
bad = 0
print(f"{'name':<18} {'n':>4} {'bit':>5} {'max_abs':>12} {'max_rel':>12}")
while i < len(lines):
    name = lines[i].strip(); cnt = int(lines[i + 1].strip())
    vals = lines[i + 2 : i + 2 + cnt]
    i += 2 + cnt
    rv = np.array([float(v) for v in vals])
    pv = np.asarray(py[name], dtype=float).ravel()
    if rv.shape != pv.shape:
        print(f"{name:<18} SHAPE MISMATCH {rv.shape} vs {pv.shape}")
        ok = False
        bad += 1
        continue
    # NaN parity: both sides NaN at the same positions is a MATCH (these
    # are R's domain-error positions); only finite pairs are compared.
    nanmask = np.isnan(rv) | np.isnan(pv)
    d = np.abs(rv - pv)
    rel = d / np.maximum(np.abs(rv), 1e-300)
    bit = int((rv == pv).sum()) + int((np.isnan(rv) & np.isnan(pv)).sum())
    dn = int(nanmask.sum())
    finite = ~nanmask
    dmax = d[finite].max() if finite.any() else float("nan")
    rmax = rel[finite].max() if finite.any() else float("nan")
    print(f"{name:<18} {cnt:>4} {bit:>5} {dmax:>12.3e} {rmax:>12.3e}"
          + (f"  (both-nan x{dn})" if dn else ""))
    fail = (nanmask.any() and not (np.isnan(rv) == np.isnan(pv)).all()) or (
        finite.any()
        and not np.allclose(rv[finite], pv[finite], rtol=1e-12, atol=1e-14))
    if fail:
        ok = False
        bad += 1
        j = int(np.argmax(d))
        print(f"   FAIL {name}[{j}]: R={rv[j]!r} PY={pv[j]!r}")
print(f"TOTAL BAD: {bad}")
sys.exit(0 if ok else 1)
